version: "2.1"
orbs:
  docker: circleci/docker@0.5.13

jobs:
  set_image_tag:
    docker:
      - image: bash:5
    steps:
      - checkout
      - run:
          name: set image tag 
          command: |
            if [ $CIRCLE_BRANCH == "master" ]; then
              echo 'export IMAGE_TAG=$(echo $CIRCLE_TAG | tr -d v)' >> $BASH_ENV
            else
              echo 'export IMAGE_TAG=$CIRCLE_BRANCH' >> $BASH_ENV
            fi
  show_image_tag:
    docker:
      - image: bash:5
    steps:
      - checkout
      - run: echo IMAGE_TAG is $IMAGE_TAG

workflows:
  build-and-publish-docker-image:
    jobs:
      - set_image_tag:
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
      - show_image_tag:
          requires:
            - set_image_tag
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
      - docker/publish:
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $IMAGE_TAG
          registry: modusbox-mbx-docker.jfrog.io
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
          requires:
            - set_image_tag
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
