version: "2.1"
orbs:
  docker: circleci/docker@0.5.13

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          before_build:
            - run:
                name: set image tag 
                command: |
                  if [[ -v $CIRCLE_TAG]] && [[ -v $CIRCLE_BRANCH ]]; then
                    echo "tagging a feature branch is not permitted"
                    exit 1
                  fi
                  if [[ -v $CIRCLE_TAG ]]; then
                    echo 'export IMAGE_TAG=$(echo $CIRCLE_TAG | tr -d v)' >> $BASH_ENV
                  elif [[ -v $CIRCLE_BRANCH ]]; then 
                    echo 'export IMAGE_TAG=$CIRCLE_BRANCH' >> $BASH_ENV
                  else
                    echo "ABORTING. Neither git tag nor feature branch found"
                    exit 1
                  fi
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $IMAGE_TAG
          registry: modusbox-mbx-docker.jfrog.io
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - master
